version: '3'
services:
  app:
    build: ./conf/api
    ports:
      - "127.0.0.1:8888:8888"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8888

  front:
    build: ./conf/front
    ports:
      - "127.0.0.1:80:8080"
    command: npm run serve
